-- ============================================
-- Cipher Note: Development Seed Data
-- ============================================
-- This file is run by `supabase db reset` and `supabase start`.
-- It creates test users with properly formatted placeholder crypto values
-- for local development and testing.
--
-- Two test users are created for RLS verification:
--   1. "testuser" — the primary development test user
--   2. "alice" — a second user for cross-user RLS testing
--
-- Crypto value sizes (hex chars, matching CHECK constraints):
--   salts:            64 chars (32 bytes)
--   IVs:              24 chars (12 bytes, AES-GCM standard)
--   wrapped keys:     96 chars (48 bytes = 32 byte ciphertext + 16 byte GCM auth tag)
--   encrypted blobs:  variable, minimum 32 chars (16 byte GCM auth tag)
--
-- Note: Crypto values are placeholders, not real Argon2id/AES-256-GCM outputs.
-- Real values will be generated by the registration flow in Steps 19-23.
-- ============================================

-- ============================================
-- Insert auth.users (Supabase Auth)
-- The trigger on_auth_user_created will auto-insert into public.users.
-- We use crypt() for encrypted_password because Supabase Auth requires bcrypt.
-- The actual password values are irrelevant for seed data — the app uses
-- Argon2id-derived auth_hashes, not direct password login.
-- ============================================

INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_user_meta_data,
  created_at,
  updated_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a'::uuid,
  'authenticated',
  'authenticated',
  'testuser@ciphernote.internal',
  crypt('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', gen_salt('bf')),
  now(),
  '{"username": "testuser"}',
  now(),
  now()
);

INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_user_meta_data,
  created_at,
  updated_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b'::uuid,
  'authenticated',
  'authenticated',
  'alice@ciphernote.internal',
  crypt('bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', gen_salt('bf')),
  now(),
  '{"username": "alice"}',
  now(),
  now()
);

-- Ensure public.users rows exist (in case the trigger didn't fire during seed)
INSERT INTO public.users (id, username, created_at)
VALUES
  ('a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a', 'testuser', now()),
  ('b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b', 'alice', now())
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- Keys for testuser
-- 32 bytes = 64 hex chars for salts
-- 12 bytes = 24 hex chars for IVs
-- 48 bytes = 96 hex chars for wrapped keys (32 byte key + 16 byte GCM tag)
-- ============================================
INSERT INTO public.keys (user_id, auth_salt, key_salt, wrapped_master_key, master_key_iv)
VALUES (
  'a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a',
  '57f8224006f5ffe8caa77918877811a28e589325bc2f819e76efc3624bce2593',
  'e5480adac4d241406a29a320896bef268ebcea25fe0ea378b95f2ecdac7dcb3b',
  '80241001ef027018028278406a4d886f766ca4cf00d011401fe8dcc40cb4af6657516cfcdfe624455c3709ab8844bf26',
  '9b89cb38693b20b0bf67c3fc'
);

-- Keys for alice
INSERT INTO public.keys (user_id, auth_salt, key_salt, wrapped_master_key, master_key_iv)
VALUES (
  'b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b',
  '2209418feadb8df5d56bf11984e9cd1a0089097db624fcacb72065226df6d9c2',
  '52555a7b430c1ce5d2624e07ef49ae80b3ee0b5dfcc2936d1f4deb75ceccb601',
  'fa63f8aee5b437fa787ca38fd93701606f05fc56ad96a565580dbf39ee6845c9f131604b8213d119b33075fd68d5dbd0',
  '2161bd83d7de15f2ea96bf6c'
);

-- ============================================
-- Field keys for testuser (all three fields, version 1)
-- ============================================
INSERT INTO public.field_keys (user_id, field_name, version, wrapped_key, key_iv)
VALUES
  ('a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a', 'note', 1, '3da22b5d01dce69a9740f9a1ada69f16266ebc13d2bad3ad50207a775d82b0e78fcdf10dd92baa0924a1d47ed694128e', 'a845853034f3b32a2428afa6'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a', 'website', 1, '77282c8d454f8559561731e7c372e80a7f1ae4128bb58f83caa2486c6aaaeff34d10b48349fee1523fdf3ddb2f39a7bf', '273a8b69f004027ac7a92d13'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a', 'email', 1, 'f6b5e69cc123b95e3685204bf3ac4d4afc069731f7b08a4604e2c0146b7011d2eec7ce11f47ccfff45bee47ff1fb3a76', '45920fa1838ceeef5e916659');

-- Field keys for alice (all three fields, version 1)
INSERT INTO public.field_keys (user_id, field_name, version, wrapped_key, key_iv)
VALUES
  ('b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b', 'note', 1, '46555c869b67bcababd1c8dc16ea07118a71aeb94aa9d1771d1e1a5b7c052fd99ac5b2ed7fd0d6450cdbb1fd5f11e35d', 'c5ce0f0a8a2604fbf2613f46'),
  ('b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b', 'website', 1, '6588d70ce0ebc957328edfc0aa2c6e04fcea189ea1a59aa7f44c6241c9a6f8e6ca169b3e424ec60d88b0a9c7ffc01b85', 'a345cfe5ed9e1ac48c4e26b6'),
  ('b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b', 'email', 1, 'f0ae4bcd96eb1f8e5639d5d1f2cd55fc049997b01ac191325004a5f375e46f17b4b65a4008e0b54cc15b789ada0e8663', '0c63b642568b4ff8f4ff854e');

-- ============================================
-- Encrypted fields for testuser (placeholder ciphertext)
-- ============================================
INSERT INTO public.encrypted_fields (user_id, field_name, encrypted_blob, iv)
VALUES
  ('a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a', 'note', '92bedd6cc3bbbd3f7a22938529fb6cfe5ef65493b647585ddb21f2bcf8257259569a4a200167e1a8dc3c14b7c573c342', '48404b45542d3a24d7ad385f'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a', 'website', 'eb2f444709b53132a7ed17bc22e822f46a20a96325e40745dc074d4a46f95569', '37d6708020fc11da275336d0'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a', 'email', '6d691e7460cdb5580a55b9c271b5be3f7578d173a1ae55a849645ab3c5c1b929', '700d6a6c3f4ab2863b94e88b');

-- Encrypted fields for alice
INSERT INTO public.encrypted_fields (user_id, field_name, encrypted_blob, iv)
VALUES
  ('b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b', 'note', '482e510787a5ac9819388ee194bc78b61a0c772b4fde3c542adf64ee36696523d6b4d396367eba6282af78931cf959fa617bb60555714f73662493a45850e514', 'e59b40c4528acd97e2ccc5af'),
  ('b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b', 'website', 'dad4ebf602fcf753b4402ebe1a30013da9ea9ad80c247aeee50da561e9786e1d0c13e809406c7379', '653343ab676c2ee3932f3662'),
  ('b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b', 'email', '08fdfd868e01f88bfd523da8cfa756c68ef3a3d99fa8843d3acd471f1a75663d', '2ee4c775a3f20911504f05bb');

-- ============================================
-- Recovery data for testuser
-- ============================================
INSERT INTO public.recovery (user_id, recovery_salt, wrapped_master_key, recovery_iv)
VALUES (
  'a0eebc99-9c0b-4ef8-bb6d-6bb6513e5e0a',
  '677f39e619bd8cb8dfd5477b74ae4bc0abd52b87623f954eb73e179941b3d0d4',
  '429cebd164ca2acbb6ad61b7aaf0895b23233628beb8b9970570742faef3c8eb86b3a472635e19971b2c64f739284874',
  'b8948164ce36c6742ecafac7'
);

-- Recovery data for alice
INSERT INTO public.recovery (user_id, recovery_salt, wrapped_master_key, recovery_iv)
VALUES (
  'b1eebc99-9c0b-4ef8-bb6d-6bb6513e5e0b',
  '1ff63f31e36c0259f57fcd842a9128193a08fa5bbdfc38d4baba844670ca79c1',
  '2fe9ca73258f574a68cd8dbe63e9793833c7f618608a0d72795cf02ad9bda1c905254cfffad60bb86da287e0dbf0c1c5',
  '76d190a197af06da33bc1cc8'
);